#!/usr/bin/env python3
"""Regenerate FREEZE_MANIFEST.txt.

The manifest existed before this script did, which is how its header came to
claim "86 files" while carrying 82 hashes: the count was written by hand and
the file list was not. Generating both from one traversal makes that class of
drift impossible, and writing the scope into the header makes the exclusions
auditable rather than implicit.
"""

import hashlib
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# what a referee needs to re-derive every printed number: the sources that
# produce the values, the values themselves, the tests that bind them, and the
# manuscript that prints them.
INCLUDE = [
    ("manuscript", ("*.tex", "*.pdf", "supplementary.aux")),
    ("manuscript/figures", ("*.pdf",)),
    ("manuscript", ("make_*.py",)),
    ("qbscreen", ("*.py",)),
    ("qbscreen/tests", ("*.py",)),
    ("simulation_results", ("*.json",)),
    ("simulation_results/panel", ("*.json",)),
    # the DAS names regenerate_all.sh as the script that certifies reproduction,
    # so it must itself be frozen; *.py alone silently excluded it
    ("scripts", ("*.py", "*.sh")),
    (".", ("README.md", "pyproject.toml")),
    # claims-ledger.md carries the evidence type of every claim and is now
    # maintained by sync_test_counts.py; leaving it unfrozen meant the count
    # guard could be satisfied while the file itself was edited undetected
    ("manuscript", ("claims-ledger.md",)),
    # the PCCP table-of-contents entry and the upload checklist are shipped
    # artefacts, not build products: the .tif and the 250-character .txt are
    # uploaded as-is, so they are frozen alongside the .pdf that *.pdf catches
    ("manuscript", ("toc_entry.tif", "toc_entry.txt", "SUBMISSION_CHECKLIST.md")),
]

# LaTeX logs and .aux files are deliberately out of scope: they embed absolute
# paths and timestamps, so they differ between machines and would make the
# manifest fail for a referee who merely recompiled.
EXCLUDE_NOTE = ("LaTeX build products (.log, .out, .bbl, and every .aux but "
                "supplementary.aux) are excluded: they embed absolute paths and "
                "timestamps and so are not reproducible across machines. "
                "supplementary.aux is kept because it is a test input -- it carries "
                "the table numbers LaTeX assigned, which the cross-document "
                "reference test checks against -- and it contains no absolute paths. "
                "adversarial-review-log.md and manuscript-REVIEW.md are process "
                "history, not submitted artefacts, and are deliberately not frozen. "
                "figures/fig_baseline.pdf is frozen because qrc_benchmarks.py "
                "produces it, but no manuscript figure uses it.")


def collect():
    seen, out = set(), []
    for sub, pats in INCLUDE:
        d = ROOT / sub
        if not d.is_dir():
            continue
        for pat in pats:
            for f in sorted(d.glob(pat)):
                rel = f.relative_to(ROOT).as_posix()
                if not f.is_file() or rel in seen:
                    continue
                seen.add(rel)
                out.append(rel)
    return sorted(out)


def main():
    files = collect()
    pytest = subprocess.run([sys.executable, "-m", "pytest", "qbscreen/tests/", "-q"],
                            cwd=ROOT, capture_output=True, text=True)
    summary = [l for l in pytest.stdout.strip().splitlines() if "passed" in l or "failed" in l]

    lines = ["# Freeze manifest",
             "# generated by scripts/freeze.py",
             # the summary line carries a wall-clock duration, which made the
             # manifest differ on every run -- the same non-reproducibility the
             # LaTeX logs are excluded for. Keep the counts, drop the seconds.
             f"# pytest: {re.sub(r' in [0-9.]+s', '', summary[-1]) if summary else 'not run'}"
             f" (exit {pytest.returncode})",
             f"# scope: {len(files)} files -- manuscript sources, PDFs and",
             "#        supplementary.aux; embedded figure PDFs and their generators; the",
             "#        qbscreen package and its tests; every simulation_results JSON they",
             "#        read or write; the PCCP TOC entry and submission checklist;",
             "#        README.md; pyproject.toml; and scripts/.",
             f"# note:  {EXCLUDE_NOTE}",
             ""]
    for rel in files:
        h = hashlib.sha256((ROOT / rel).read_bytes()).hexdigest()
        lines.append(f"{h}  {rel}")

    (ROOT / "FREEZE_MANIFEST.txt").write_text("\n".join(lines) + "\n")
    print(f"wrote FREEZE_MANIFEST.txt: {len(files)} files, pytest exit {pytest.returncode}")
    return 0 if pytest.returncode == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
